simplemooc/simplemooc/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contato/', views.contact, name='contact'),
    
]

simplemooc/simplemooc/forum/urls.py
from django.urls import path, re_path

from . import views


app_name = 'forum'

urlpatterns = [
    path('', views.ForumView.as_view(), name='index'),
    re_path(r'^tag/(?P<tag>[\w_-]+)',
            views.ForumView.as_view(),
            name='tagged_index'),
    re_path(r'^respostas/(?P<pk>\d+)/correta/',
            views.CorrectReplyView.as_view(),
            name='correct_reply'),
    re_path(r'^respostas/(?P<pk>\d+)/incorreta/',
            views.CorrectReplyView.as_view(correct=False),
            name='incorrect_reply'),
    re_path(r'^(?P<slug>[\w_-]+)',
            views.ThreadView.as_view(),
            name='thread'),
    ]

simplemooc/simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('conta/', include('simplemooc.account.urls', namespace='account')),
    path('forum/', include('simplemooc.forum.urls', namespace='forum')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

simplemooc/simplemooc/forum/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from taggit.managers import TaggableManager


class Thread(models.Model):
    title = models.CharField('Título', max_length=100)
    slug = models.SlugField('Identificador', max_length=100, unique=True)
    body = models.TextField('Mensagem')
    views = models.IntegerField('Visualizações', blank=True, default=0)
    answers = models.IntegerField('Respostas', blank=True, default=0)
    tags = TaggableManager()

    created_at = models.DateTimeField(
        verbose_name='Criado em',
        auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name='Atualizado em',
        auto_now=True)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Autor',
        on_delete=models.CASCADE,
        related_name='threads')

    def get_absolute_url(self):
        return reverse('forum:thread', args=[self.slug])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['-updated_at']


class Reply(models.Model):
    reply = models.TextField('Resposta')
    correct = models.BooleanField('Correta?', blank=True, default=False)

    created_at = models.DateTimeField(
        verbose_name='Criado em',
        auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name='Atualizado em',
        auto_now=True)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Autor',
        on_delete=models.CASCADE,
        related_name='replies')

    thread = models.ForeignKey(
        Thread,
        verbose_name='Tópico',
        related_name='replies',
        on_delete=models.CASCADE)

    def __str__(self):
        return self.reply[:100]

    class Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = 'Respostas'
        ordering = ['-correct', 'created_at']


def post_save_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()
    if instance.correct:
        instance.thread.replies.exclude(pk=instance.pk).update(correct=False)


def post_delete_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()


models.signals.post_save.connect(
    post_save_reply, sender=Reply, dispatch_uid='post_save_reply'
    )


models.signals.post_delete.connect(
    post_delete_reply, sender=Reply, dispatch_uid='post_delete_reply'
    )

simplemooc/simplemooc/forum/forms.py
from django import forms

from .models import Reply


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['reply']

simplemooc/simplemooc/forum/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.contrib import messages

from .models import Thread, Reply
from .forms import ReplyForm


class ForumView(ListView):
    paginate_by = 2
    template_name = 'index.html'

    def get_queryset(self):
        queryset = Thread.objects.all()
        order = self.request.GET.get('order', '')

        if order == 'views':
            queryset = queryset.order_by('-views')
        elif order == 'answers':
            queryset = queryset.order_by('-answers')

        if 'tag' in self.kwargs:
            tag = self.kwargs['tag']
            queryset = queryset.filter(tags__slug__in=[tag])

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        return context


class ThreadView(DetailView):
    model = Thread
    template_name = 'thread.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        thread = context['object']
        context['tags'] = Thread.tags.all()
        context['form'] = ReplyForm(self.request.POST or None)
        context['replies'] = thread.replies.all().order_by('-created_at')

        return context

    def get(self, request, *args, **kwargs):
        response = super(ThreadView, self).get(request, *args, **kwargs)
        if not request.user.is_authenticated or \
           (self.object.author != request.user):
            self.object.views = self.object.views + 1
            self.object.save()
        return response

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request,
                           'Voce deve estar logado  adicionar uma resposta')
            return redirect(request.path)

        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = context['form']
        if form.is_valid():
            reply = form.save(commit=False)
            reply.thread = self.object
            reply.author = request.user
            reply.save()
            messages.success(request, 'Resposta criada com sucesso')
            context['form'] = ReplyForm
        return self.render_to_response(context)


class CorrectReplyView(View):

    correct = True

    def get(self, request, pk):
        reply = get_object_or_404(
            Reply,
            pk=pk,
            thread__author=self.request.user)

        reply.correct = self.correct
        reply.save()
        return redirect(reply.thread.get_absolute_url())

simplemooc/simplemooc/forum/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="fas fa-sync-alt"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fas fa-comments"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:tagged_index' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% for thread in object_list %}
            <div class="well">
                <h3><a href="" title="">{{ thread.title }}</a></h3>
                <h5>
                    Criado por {{ thread.author }}
                    | {{ thread.answers }} resposta{{ thread.answers|pluralize }}
                    | {{ thread.views }} Visualizaç{{ thread.views|pluralize:"ão,ões" }}
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    Tags:
                    {% for tag in thread.tags.all %}
                        <a href="{% url 'forum:tagged_index' tag.slug %}" title="">{{ tag }}</a>
                        {% if not forloop.last%},{% endif %}
                    {% endfor %}

                    <a class="fright" href="" title="">
                        Atualizado a {{ thread.updated_at|timesince }} atrás.
                    </a>
                </p>
            </div>
            {% endfor %}
            <ul class="pagination pagination-centered">
                {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.order %}&order={{request.GET.order}}{% endif %}" title="">
                        Anterior
                    </a>
                </li>
                {% endif %}
                {% for page in paginator.page_range %}
                <li
                    {% if page == page_obj.number %}
                    class="active"
                    {% endif %}
                >
                    <a href="?page={{ page }}{% if request.GET.order %}&order={{request.GET.order}}{% endif %}" title="">{{ page }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}{% if request.GET.order %}&order={{request.GET.order}}{% endif %}" title="">
                        Próxima
                    </a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/simplemooc/forum/templates/thread.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
            <li>/</li>
            <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Tópicos do Fórum
                </li>
                <li>
                    <a href="?order=">
                        <i class="fas fa-sync-alt"></i>
                        Mais Recentes
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        Mais Visualizados
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fas fa-comments"></i>
                        Mais Comentados
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:tagged_index' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            <div class="well">
                <h2>{{ object }}</h2>
                {{ object.body|linebreaks }}
                <h5>Criado por {{ object.author }}</h5>
                <p>
                    <i class="fa fa-tags"></i>
                    {% for tag in object.tags.all %}
                    <a href="{% url 'forum:tagged_index' tag.slug %}" title="">{{ tag }}</a>
                    {% if not forloop.last%},{% endif %}
                    {% endfor %}
                    <a class="fright" href="{{ object.get_absolute_url }}">
                        Criado a {{ object.created_at|timesince }} atrás.
                    </a>
                </p>
            </div>
            <div class="well">
                <h4 id="comments">Respostas
                    <a class="fright" href="#add_comment">Responder</a>
                </h4>
                {% for reply in replies %}
                <hr />
                <p>
                    <strong>{{ reply.author }}</strong> disse à {{ reply.created_at|timesince }} atrás:
                    {{ reply.reply|linebreaksbr }}
                </p>
                <p>
                    {% if reply.correct %}
                        {% if object.author == user %}
                        <a href="{% url 'forum:incorrect_reply' reply.pk %}" class="pure-button button-error">
                            Cancelar resposta correta
                        </a>
                        {% endif %}
                        <span class="fright label-success">
                            Resposta indicada pelo autor
                        </span>
                        <br />
                    {% elif object.author == user %}
                        <a href="{% url 'forum:correct_reply' reply.pk %}"class="pure-button button-success">
                            Resposta correta
                        </a>
                    {% endif %}
                </p>
                {% endfor %}
                <hr />
                <form method="POST" class="pure-form pure-form-stacked" id="add_comment">
                    <fieldset>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">
                                Enviar
                            </button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}