simplemooc/simplemooc/account/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'account'

urlpatterns = [
    path('entrar/',
        LoginView.as_view(template_name="accounts/login.html"),        
        name='login'
    ),
    path('sair/',
        LogoutView.as_view(next_page="core:home"),        
        name='logout'
    ),
    path('cadastre-se', views.register, name='register'),
    path('', views.dashboard, name='dashboard'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit_password'),
    path('resetar-senha/', views.password_reset, name='password_reset'),
    re_path(r'^nova-senha/(?P<key>\w+)/$', views.password_reset_confirm,
        name='password_reset_confirm'),
]

simplemooc/simplemooc/courses/urls.py
from django.urls import path, re_path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/inscricao/$',
            views.enrollment,
            name='enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/$',
            views.announcements,
            name='announcements'),
    re_path(r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$',
            views.undo_enrollment,
            name='undo_enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$',
            views.announcement,
            name='announcement'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/$',
            views.lessons,
            name='lessons'),
    re_path(r'^(?P<slug>[\w_-]+)/aula/(?P<pk>\d+)/$',
            views.lesson,
            name='lesson'),
    re_path(r'^(?P<slug>[\w_-]+)/material/(?P<pk>\d+)/$',
            views.material,
            name='material'),
]

simplemooc/simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('conta/', include('simplemooc.account.urls', namespace='account')),
    path('forum/', include('simplemooc.forum.urls', namespace='forum')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

simplemooc/simplemooc/account/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser,
                                        PermissionsMixin, UserManager)
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome de usuário',
        max_length=30,
        unique=True,
        validators=[validators.RegexValidator(
            re.compile('^[\w]+$'),
            "O nome de usuário só pode conter letras e números.",
            "invalid")]
        )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está Ativo?', blank=True,
                                    default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True,
                                   default=False)
    date_joined = models.DateTimeField('Data de inscrição',
                                       auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"


class PasswordReset(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Usuário',
        on_delete=models.CASCADE
        )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField(
        'Confirmado',
        default=False,
        blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = "Nova Senha"
        verbose_name_plural = "Novas Senhas"
        ordering = ["-created_at"]

simplemooc/simplemooc/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from simplemooc.core.utils import generate_hash_key
from simplemooc.core.mail import send_mail_template
from .models import PasswordReset

User = get_user_model()

class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label="Senha", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmação de Senha", 
                        widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                "As senhas informadas não conferem",
                code="password_mismatch"
            )

            return password2
    
    def save(self, commit=True):    
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
        
        return user
    
    class Meta:
        model = User
        fields = ['username', 'email']

class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["username", "email", "name"]

    def clean_email(self):
        email = self.cleaned_data["email"]
        queryset = User.objects.filter(email=email).exclude(pk=self.instance.pk)

        if queryset.exists():
            raise forms.ValidationError("Já existe um usuário com este email")
        
        return email

class PasswordResetForm(forms.Form):

    email = forms.EmailField(label="E-mail")

    def clean_email(self):
        email = self.cleaned_data["email"]
        queryset = User.objects.filter(email=email)

        if queryset.exists():        
            return email
        
        raise forms.ValidationError("Não existe usuário com este email.")
    
    def save(self):
        user = User.objects.get(email=self.cleaned_data["email"])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = "accounts/password_reset_mail.html"
        subject = "Criar nova senha no Simple MOOC"
        context = {
            "reset": reset,
        }

        send_mail_template(subject, template_name, context, [user.email])

simplemooc/simplemooc/account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib import messages

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset


@login_required
def dashboard(request):
    template_name = "accounts/dashboard.html"

    return render(request, template_name)


@login_required
def edit(request):
    template_name = "accounts/edit.html"
    context = {}

    if request.method == "POST":
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            message = "Seus dados foram alterados com sucesso."
            messages.success(request, message)
            return redirect('account:dashboard')
    else:
        form = EditAccountForm(instance=request.user)

    context["form"] = form

    return render(request, template_name, context)


@login_required
def edit_password(request):
    template_name = "accounts/edit_password.html"
    context = {}

    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context["success"] = True
    else:
        form = PasswordChangeForm(user=request.user)

    context["form"] = form

    return render(request, template_name, context)


def password_reset(request):
    template_name = "accounts/password_reset.html"
    form = PasswordResetForm(request.POST or None)
    context = {}

    if form.is_valid():
        form.save()
        context["success"] = True

    context["form"] = form

    return render(request, template_name, context)


def password_reset_confirm(request, key):
    template_name = "accounts/password_reset_confirm.html"
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)

    if form.is_valid():
        form.save()
        context["success"] = True

    context["form"] = form

    return render(request, template_name, context)


def register(request):
    template_name = "accounts/register.html"
    context = {}

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data["password1"])
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()

    context["form"] = form

    return render(request, template_name, context)

simplemooc/simplemooc/account/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'account:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Bem-vindo, {{ user }}!
                </li>
                {% block menu_options %}
                {% my_courses user %}
                <li class="pure-menu-heading">Conta</li>
                <li>
                    <a href="{% url 'account:edit' %}">
                        <i class="fas fa-cog"></i>
                        Editar Conta
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:edit_password' %}">
                        <i class="fas fa-lock"></i>
                        Editar Senha
                    </a>
                </li>
                {% endblock %}
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <h2>Meus Cursos</h2>
            {% load_my_courses user as enrollments %}
            {% for enrollment in enrollments %}
            <div class="well">
                <h3>{{ enrollment.course }}
                    ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data de início.' }})
                </h3>
                {{ enrollment.course.description|linebreaks }}
                <div class="pure-controls">
                    <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">
                        Acessar
                    </a>
                    <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="pure-button button-error">
                        Cancelar
                    </a>
                </div>
            </div>
            {% empty %}
            <aside class="pure-u-1">
                <p>Nenhum curso inscrito.</p>
            </aside>
            {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/simplemooc/account/templates/accounts/edit.html
{% extends 'accounts/dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'account:edit' %}">Editar minha conta</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
        <p>Os dados foram alterados com Sucesso!</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}

        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/simplemooc/account/templates/accounts/edit_password.html
{% extends 'accounts/dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'account:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
        <p>Senha alterada com Sucesso!</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}

        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/simplemooc/account/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors}}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">
                        Entrar
                    </button>
                </div>
            </fieldset>
            <p>
                Não é Cadastrado? <a href="{% url 'account:register' %}" title="">Cadastre-se</a> <br>
                Esqueceu a senha? <a href="{% url 'account:password_reset' %}" title="">Nova senha</a> <br>
            </p>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/simplemooc/account/templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
            <p>Um email foi enviado com instruções para 
                resetar sua senha
            </p>
        {% else %}
            <h2>Informe seu email</h2>
            <form class="pure-form pure-form-aligned" method="post">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors}}

                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">
                            Enviar E-mail
                        </button>
                    </div>
                </fieldset>
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/simplemooc/account/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        {% if success %}
            <p>Senha alterada com Sucesso!</p>
        {% else %}
            <h2>Informe sua nova senha</h2>
            <form class="pure-form pure-form-aligned" method="post">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors}}

                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">
                            Enviar
                        </button>
                    </div>
                </fieldset>
            </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/simplemooc/account/templates/accounts/password_reset_mail.html
<p>
    Para criar uma nova senha, acesse o link: 
    <a 
        href="http://127.0.0.1:8000{% url 'account:password_reset_confirm' reset.key %}" 
        title="new-passwd">
        Criar nova senha
    </a>
</p>

simplemooc/simplemooc/account/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors}}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">
                        Cadastrar
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}